server:
  port: 8084
spring:
  application:
    name: Api-Gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/v1/order/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false