server:
  port: 8083
spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://postgres:5432/customer_order
    username: "okayreet"
    password: "password"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

rabbitmq:
  exchanges:
    order-exchange: order-exchange
    notification-exchange: notification-exchange
  queues:
    order-queue: order-queue
    notification-queue: notification-queue
  routing-keys:
    order-routing-key: order-routing-key
    notification-routing-key: notification-routing-key